model:
  arch: vit_small
  patch_size: 8
  pre_training: dino

peekaboo:
  feats: "k"

training:
  dataset: DUTS-TR
  dataset_set: null

  # Hyper params
  seed: 0
  max_iter: 500
  nb_epochs: 3
  batch_size: 50
  lr0: 5e-2
  step_lr_size: 50
  step_lr_gamma: 0.95

  # Augmentations
  crop_size: 224
  scale_range: [0.1, 3.0]
  photometric_aug: gaussian_blur
  proba_photometric_aug: 0.5
  cropping_strategy: random_scale

evaluation:
  type: saliency
  datasets: [DUT-OMRON, ECSSD]
  freq: 50